version: '3'
services:
   web:                     #to define the node.js app
     build:  .              #to point it to the current working directory (docker file)
     ports:      
       - "3000:3000"        #port forwarding configuration
     environment:
      DATABASE_URL: ${DATABASE_URL}